name: Test Wabbi Gate Pass

on: [pull_request]

jobs:
  pull_request_job:
    runs-on: ubuntu-latest
    name: Verify Wabbi Gate Pass
    steps:
      - name: verify wabbi gate status is pass
        id: process_pr
        uses: hiwabbi/wabbi-gate-by-issues@v0.5.5
        with:
          wabbiHost: https://qa.wabbi.io
          wabbiProjectId: 1
          issuePrefixes: AB,AC,AD
          wabbiGateId: 14
          wabbiGateToken: ${{ secrets.GATE_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Display wabbi gate status
        run: echo "pr process status ${{ steps.process_pr.outputs.status }}"
